services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor

    ports:
      - "8000:80"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: ${APP_KEY}
      APP_URL: http://localhost
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: openhackathon
      DB_USERNAME: root
      DB_PASSWORD: root
      SESSION_DRIVER: database
      CACHE_DRIVER: file
      QUEUE_DRIVER: database
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: openhackathon
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=localhost", "--user=root", "--password=root"]
      interval: 10s
      retries: 5

volumes:
  db_data:
